version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    container_name: netology_test
    environment:
      - node.name=es
      - cluster.name=netology_test
      - network.host=0.0.0.0
      - http.port=9200
      - discovery.seed_hosts=127.0.0.1
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
volumes:
  esdata:
    driver: local
  
networks:
   esnet:
    driver: bridge