version: '2'
services:
  es:
    image: konstantinpe4enkin/myes:test
    container_name: netology_test
    environment:
      - cluster.name=netology_test
      - network.host=0.0.0.0
      - discovery.seed_hosts=127.0.0.1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
volumes:
  esdata:
    driver: local
  
networks:
   esnet: