- hosts: front
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    k0pec
  roles:
   - Install_Nginx_LetsEncrypt
   - Install_Proxy
   - Install_Node_Exporter
