- hosts: db app gitlab runner monitoring
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    k0pec
  roles:
   - Install_Node_Exporter

  environment:
     http_proxy: http://pe4enki2n.space:8118
     https_proxy: http://pe4enki2n.space:8118
