- hosts: app
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    k0pec
  vars:
    - domain: "pe4enki2n.space"
    - download_url: "http://wordpress.org/latest.tar.gz"
    - wpdirectory: "/var/www"
 
  roles:
   - nginx
   - memcached
   - php5
   - wordpress

  environment:
     http_proxy: http://pe4enki2n.space:8118
     https_proxy: http://pe4enki2n.space:8118

